// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfv8ON8MeG6h46RPBxHWjpwFJikULlFQs',
    appId: '1:869377962935:web:adcddb538247a711ef6e32',
    messagingSenderId: '869377962935',
    projectId: 'habi-17b3e',
    authDomain: 'habi-17b3e.firebaseapp.com',
    storageBucket: 'habi-17b3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3p3ML0JKIbQejRTcloVHn_IUwI5S_9Rs',
    appId: '1:869377962935:android:c684c27c140e6375ef6e32',
    messagingSenderId: '869377962935',
    projectId: 'habi-17b3e',
    storageBucket: 'habi-17b3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJrfY7u7tyiJ38OppKL6VB84YDzvB16Uw',
    appId: '1:869377962935:ios:23137089f1d598b3ef6e32',
    messagingSenderId: '869377962935',
    projectId: 'habi-17b3e',
    storageBucket: 'habi-17b3e.firebasestorage.app',
    iosBundleId: 'com.example.habiTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJrfY7u7tyiJ38OppKL6VB84YDzvB16Uw',
    appId: '1:869377962935:ios:23137089f1d598b3ef6e32',
    messagingSenderId: '869377962935',
    projectId: 'habi-17b3e',
    storageBucket: 'habi-17b3e.firebasestorage.app',
    iosBundleId: 'com.example.habiTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfv8ON8MeG6h46RPBxHWjpwFJikULlFQs',
    appId: '1:869377962935:web:6c1144783c0094caef6e32',
    messagingSenderId: '869377962935',
    projectId: 'habi-17b3e',
    authDomain: 'habi-17b3e.firebaseapp.com',
    storageBucket: 'habi-17b3e.firebasestorage.app',
  );
}
